# Generated by Django 5.1.7 on 2025-04-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_userprofile_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sms_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
